"""Every knob ``infer_directory`` accepts must appear in the run manifest.

Two flags shipped without ever being recorded, and each time the omission was
found only after an arm's behaviour had already been argued about:

  * ``index_filler`` (found 2026-09-06) decides whether label 0 -- roughly a
    third of the frames -- is retrievable at all.  Runs ``t_v3`` and
    ``t_barfull`` cannot say from their own manifests which way it was set.
  * ``draft_facing_anchor`` and ``derive_retrieval_group`` (found 2026-09-07).
    With them absent, ``runs/t_v4/final`` and ``runs/t_bfa/a0p6`` differed in
    exactly one recorded key -- ``completion_keep_root`` -- even though the
    second was launched to test the facing anchor.  The evidence that the
    anchor had run at all was the directory name someone typed.

This is the mirror image of the failure ``test_seam_blend_window.py`` guards.
That one catches a flag that is recorded but never reaches the code; this one
catches a flag that reaches the code but is never recorded.  Both leave a run
whose artifact does not describe it, and the second is worse, because the
manifest reads complete.

The check is structural on purpose.  It enumerates the parameters with ast
rather than calling the function, so it costs no GPU and cannot be satisfied by
a run that happens to leave the flag at its default.
"""

import ast
import pathlib

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
SOURCE = REPO / "infer_atomic.py"

# Parameters that are plumbing rather than knobs: they name objects the caller
# already holds, not choices that change the generated bytes.  Keep this list
# short and justify every entry -- an unjustified entry is how the next flag
# escapes.
# Every entry must be an ACTUAL parameter of infer_directory. An earlier
# version listed six names (library, planner, completion, planner_args,
# dataset, names) that were not parameters at all -- dead entries that would
# have silently pre-excused any future parameter taking one of those names.
# test_allowlist_has_no_dead_entries below keeps that from coming back.
NOT_A_SAMPLING_CHOICE = {
    # Recorded at the manifest's TOP level rather than inside "sampling".
    # They are in the artifact, just not in the sampling block -- which the
    # earlier, looser matcher could not distinguish from "recorded in
    # sampling". Verified individually against a written manifest below.
    "device",
    "output_dir",
    "planner_checkpoint",
    "completion_checkpoint",
    "music_span_check",
    "sequence_names", # the requested names; the resolved list is top-level "names"
    # Recorded in "sampling" under its CLI flag's name, retrieval_selector_join_band
    # (every fix-series manifest carries that key), not under the parameter's.
    "draft_selector_join_band",
    # Housekeeping for THIS invocation's outputs, not a property of the motion.
    # Narrower than it first reads, though: with overwrite=False the reuse
    # branch (infer_atomic.py:3597) keeps existing samples while still
    # rewriting manifest.json, and _generated_is_current compares only
    # checkpoints/protocol/provenance -- no sampling flag. So a rerun into a
    # populated directory with a changed flag and no --overwrite yields a
    # manifest describing bytes it did not produce. Recording the flag would
    # not fix that; the reuse check would have to.
    "overwrite",
    # Input locations.  data_root is recorded under "dataset_provenance" with
    # the build/normalizer/source-manifest hashes, which pins the corpus far
    # harder than the path would; the other three are read-only lookups beside
    # it, and target_motion_dir is summarised by top-level
    # "target_motion_selection".
    "data_root",
    # Both recorded at top level since 2026-09-22 ("ingest_root", "audio_dir").
    # Not lookups: the T1 and T2 eval audio differ on 20 of 20 clips (the T2
    # re-decode fixed a 161 ms / 0-46 ms early audio.wav), and the query audio
    # is the model's music conditioning.
    "ingest_root",
    "audio_dir",
    "target_motion_dir",
    # Recorded at top level as "release_binding": its per-stage status reads
    # "cross_release_allowed" exactly when this flag let a mismatch through.
    "allow_cross_release_checkpoints",
}


def _infer_directory():
    tree = ast.parse(SOURCE.read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "infer_directory":
            return node
    raise AssertionError("infer_directory not found in infer_atomic.py")


def _sampling_dict(node):
    """The dict literal that becomes manifest["sampling"], and only that one.

    An earlier version walked EVERY dict in the function, which meant a
    parameter recorded anywhere -- including the manifest's top level -- passed
    the check. That is a weaker property than the one advertised: it proved the
    name appeared somewhere, not that the run's sampling configuration was
    recorded. Today only three dicts in the function carry string keys so the
    two agree, but the looser matcher would drift the moment a fourth appears.
    """
    for sub in ast.walk(node):
        if not isinstance(sub, ast.Dict):
            continue
        for key, value in zip(sub.keys, sub.values):
            if (isinstance(key, ast.Constant) and key.value == "sampling"
                    and isinstance(value, ast.Dict)):
                return value
    raise AssertionError('no "sampling" dict literal found in infer_directory')


def _manifest_string_keys(node):
    sampling = _sampling_dict(node)
    return {k.value for k in sampling.keys
            if isinstance(k, ast.Constant) and isinstance(k.value, str)}


def _parameters(node):
    """Every parameter, including positional-only, *args and **kwargs.

    The first version read only ``args + kwonlyargs``. ``infer_directory`` has
    none of the other three today, so nothing escaped -- but a flag added as a
    positional-only parameter would have been invisible to the guard, which is
    precisely the failure class this file exists to prevent.
    """
    a = node.args
    names = [p.arg for p in a.posonlyargs + a.args + a.kwonlyargs]
    for extra in (a.vararg, a.kwarg):
        if extra is not None:
            names.append(extra.arg)
    return names


def test_every_parameter_is_written_to_the_manifest():
    node = _infer_directory()
    params = _parameters(node)
    recorded = _manifest_string_keys(node)
    missing = sorted(
        p for p in params
        if p not in NOT_A_SAMPLING_CHOICE and p not in recorded
    )
    assert not missing, (
        "infer_directory accepts {} but the manifest never records them, so a "
        "run made with them cannot be told apart from one made without. Add "
        "each to the \"sampling\" dict (or to NOT_A_SAMPLING_CHOICE with a "
        "reason).".format(missing)
    )


@pytest.mark.parametrize("flag", [
    "draft_facing_anchor",
    "derive_retrieval_group",
    "index_filler",
    "draft_bar_prototypes",
    "draft_recurrence_variety",
    "draft_seam_aware_retrieval",
    "completion_inpaint_seam_width",
    "plan_bar_tokens",
])
def test_named_flags_are_present(flag):
    """The specific flags whose absence has already cost a run.

    The general test above would catch these too; they are named separately so
    a future edit to NOT_A_SAMPLING_CHOICE cannot quietly excuse one of them.
    """
    node = _infer_directory()
    params = set(_parameters(node))
    assert flag in params, "{} is no longer a parameter of infer_directory".format(flag)
    assert flag in _manifest_string_keys(node), (
        "{} reaches the code but is not recorded in the manifest".format(flag)
    )


def test_allowlist_has_no_dead_entries():
    """Every allowlisted name must really be a parameter.

    A name in the allowlist that is not a parameter does nothing today and
    pre-excuses a future parameter that happens to take it -- the exact way the
    guard would rot without anyone editing the guard.
    """
    params = set(_parameters(_infer_directory()))
    dead = sorted(NOT_A_SAMPLING_CHOICE - params)
    assert not dead, (
        "NOT_A_SAMPLING_CHOICE lists {} which are not parameters of "
        "infer_directory; remove them so they cannot excuse a future "
        "parameter of the same name.".format(dead)
    )


def test_the_guard_actually_fails_when_a_key_is_removed():
    """The guard must be able to fail -- CLAUDE.md section 2.

    Parses a copy of the source with one sampling key deleted and asserts the
    check reports it missing. Without this the file could pass forever because
    the matcher was too loose, which is what an audit found on 2026-09-07.
    """
    source = SOURCE.read_text()
    victim = '            "draft_facing_anchor": draft_facing_anchor,\n'
    assert source.count(victim) == 1, "sampling dict no longer records draft_facing_anchor verbatim"
    node = None
    for candidate in ast.walk(ast.parse(source.replace(victim, ""))):
        if isinstance(candidate, ast.FunctionDef) and candidate.name == "infer_directory":
            node = candidate
    assert node is not None
    assert "draft_facing_anchor" in _parameters(node)
    assert "draft_facing_anchor" not in _manifest_string_keys(node), (
        "removing the key from the sampling dict did not make the guard see it "
        "as missing -- the guard cannot fail"
    )


TOP_LEVEL_INSTEAD_OF_SAMPLING = (
    "device", "output_dir", "planner_checkpoint", "completion_checkpoint",
    "music_span_check",
)


@pytest.mark.parametrize("name", TOP_LEVEL_INSTEAD_OF_SAMPLING)
def test_top_level_allowlist_entries_really_are_recorded(name):
    """Allowlisted "it's at the top level" claims must be true.

    Otherwise the allowlist becomes the hiding place the guard exists to close:
    a parameter excused with a reason nobody checked. The manifest dict is the
    one whose literal contains "sampling", so this reads the real structure
    rather than trusting the comment.
    """
    node = _infer_directory()
    manifest = None
    for sub in ast.walk(node):
        if isinstance(sub, ast.Dict) and any(
            isinstance(k, ast.Constant) and k.value == "sampling" for k in sub.keys
        ):
            manifest = sub
    assert manifest is not None, "manifest dict literal not found"
    top = {k.value for k in manifest.keys
           if isinstance(k, ast.Constant) and isinstance(k.value, str)}
    assert name in top, (
        "{} is allowlisted as 'recorded at the top level' but the manifest's "
        "top-level dict has no such key".format(name)
    )
