"""Refuse an arm whose configuration differs from its reference in more than
the key it is named after.

WHY THIS EXISTS.  On 2026-09-11 two arms named for two different flags came out
BYTE-IDENTICAL, because the flags reached only one of the two ``build_draft``
call sites -- while the scorecard printed separate numbers for them and a
conclusion was drawn from the difference.  The manifest said the flags were
set; the code never saw them.  A diff against the reference arm catches both
halves of that failure: a flag that did not change anything shows up as an
identical sampling dict, and a flag that changed something else shows up as an
unexpected key.

It compares the manifest's own ``sampling`` dict, which is what a rerun would
be reconstructed from, and it EXCLUDES nothing by default -- the caller has to
name every key it expects to move.
"""
import argparse
import hashlib
import json
import pathlib
import sys

# Derived per run rather than configured, so they are never evidence of a
# configuration difference.  Each is a function of the seed and the clip list.
# Derived per run rather than configured, so they are never evidence of a
# configuration difference.  Counters belong here too: they report what the run
# DID, and a run that did more work is not a run configured differently.  Before
# this, adding a counter made every later arm fail the gate on the counter
# instead of on the flag being swept -- a false alarm that hides the real one.
DERIVED = {"per_sample_seed", "sequence_order", "retrieval_selector_calls",
           "retrieval_selector_fallbacks", "retrieval_selector_no_predecessor",
           "feet_beat_lead_slots", "feet_beat_lead_skipped",
           "feet_beat_lead_applied", "feet_beat_lead_changed"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reference", required=True)
    ap.add_argument("--arm", required=True)
    ap.add_argument("--may-differ", action="append", default=[])
    ap.add_argument("--allow-identical-output", action="store_true",
                    help="accept an arm whose generated bytes equal the "
                         "reference's; only for a flag that is deliberately a "
                         "no-op at this setting")
    args = ap.parse_args()

    reference = json.load(open(args.reference))["sampling"]
    arm = json.load(open(args.arm))["sampling"]
    allowed = set(args.may_differ)

    problems = []
    for key in sorted(set(reference) | set(arm)):
        if key in DERIVED:
            continue
        before, after = reference.get(key, "<absent>"), arm.get(key, "<absent>")
        if before == after:
            if key in allowed:
                problems.append(
                    "{} was swept but did not move: both arms read {!r}. The "
                    "flag did not reach the code.".format(key, before))
            continue
        if key not in allowed:
            problems.append("{}: reference {!r} but arm {!r}, and it was not "
                            "declared with --may-differ".format(key, before, after))
    # THE HALF THIS GATE WAS MISSING.  It compared manifests, which is where
    # the flag is RECORDED, and not the pickles, which is where the flag has to
    # have an EFFECT.  On 2026-09-12 two swept arms passed it and were then
    # found byte-identical to their control: --draft-beat-anchor is a per-
    # segment stretch CAP, so 0.6 and 0.9 drop every pairing and change nothing.
    # The manifests differed, the dance did not, and the scorecard printed a row
    # for each -- which is exactly the defect this file exists to prevent.
    reference_dir = pathlib.Path(args.reference).parent
    arm_dir = pathlib.Path(args.arm).parent
    identical, compared = 0, 0
    for source in sorted(reference_dir.glob("*.pkl")):
        target = arm_dir / source.name
        if not target.exists():
            continue
        compared += 1
        if (hashlib.sha256(source.read_bytes()).hexdigest()
                == hashlib.sha256(target.read_bytes()).hexdigest()):
            identical += 1
    if compared and identical == compared and not args.allow_identical_output:
        problems.append(
            "all {} generated clips are BYTE-IDENTICAL to the reference, so "
            "the swept setting changed the manifest and not the dance. Check "
            "the flag's units before reading a scorecard row for this arm."
            .format(compared))

    if problems:
        print("ARM DOES NOT MATCH ITS REFERENCE:", file=sys.stderr)
        for problem in problems:
            print("  -", problem, file=sys.stderr)
        raise SystemExit(1)
    print("arm matches reference except {} -- {} of {} clips differ in bytes"
          .format(", ".join(sorted(allowed)) or "(nothing)",
                  compared - identical, compared))


if __name__ == "__main__":
    main()
